services:
  redis_exporter:
    image: redis_exporter:1.82
    build:
      context: .
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: redis://localhost:6379
      REDIS_USER: exporter
    restart: unless-stopped
